name: Run Tests

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
          - uses: actions/checkout@v3
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.node-version }}
                registry-url: "https://npm.pkg.github.com"

          - name: Install pnpm
            run: npm install -g pnpm

          - name: Run install
            run: pnpm install
            env:
                NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Run test in sub-folder
            run: pnpm run test:ci
